### ISSUE TITLE
Separate Dynamic Template to AngularJS Template

### ISSUE THREAD

**Issue by rubyrider** [rubyrider/music_cms#3]
1. https://github.com/rubyrider/music_cms/blob/master/app/views/layouts/music.html.erb#L2
Ensure the ng-app attribute is also set to our new layout.

2. Replace the dynamic code with https://github.com/rubyrider/music_cms/blob/master/app/views/layouts/music.html.erb#L86

3. The dynamic content from task 2 should be in 
app/assets/javascripts/music_apps/templates/home/index.html.erb

**Comment by sraskin** [comment]
I replace everything but dynamic part failed to load.
